#%RAML 1.0 NamedExample
value: |
           [ 
             {
               "id" : 71823678126378126,
               "FirstName":"John",
               "LastName":"Doe",
               "City": "Chicago",
               "Country":"USA"
             },
             {
               "id" : 71823678126378346,
               "FirstName":"Lorel",
               "LastName":"Epsum",
               "City": "Chicago",
               "Country":"USA"
             },
             {
               "id" : 71823678126378886,
               "FirstName":"Cathy",
               "LastName":"Doe",
               "City": "Chicago",
               "Country":"USA"
             } 
           ]