#%RAML 1.0 NamedExample
value: |
 [
  {
    "id":12783687126378,
    "productName": "Apple MacBook Pro 13.3 inch",
    "unitPrice": 1399.99,
    "package":"3 lbs"
  },
  {
    "id":12783687126379,
    "productName": "Apple MacBook Air 13.3 inch",
    "unitPrice": 799.99,
    "package":"3.6 lbs"
  },
  {
    "id":12783687126380,
    "productName": "Apple MacBook Pro 15.6 inch",
    "unitPrice": 1599.99,
    "package":"3.5 lbs"
  }
 ]