#%RAML 1.0 NamedExample
value: |
 [
   {
     "id" : 18273927198,
     "CompanyName" : "Apple",
     "ContactName" : "XYZ",
     "ContactTitle" : "Mr.",
     "City" : "San Francisco",
     "Country" : "USA",
     "Phone" : 1230987612
   },
   {
     "id" : 18273927200,
     "CompanyName" : "Samsung",
     "ContactName" : "ABC",
     "ContactTitle" : "Mr.",
     "City" : "San Jose",
     "Country" : "USA",
     "Phone" : 1230987617
   },
   {
     "id" : 18273927765,
     "CompanyName" : "Honor",
     "ContactName" : "JFK",
     "ContactTitle" : "Mrs.",
     "City" : "New York City",
     "Country" : "USA",
     "Phone" : 1230987324
   }
 ]