#%RAML 1.0
title: Order Management System
version: 1.0
baseUri: http://api.oms.com
mediaType: application/json

/order:
 get:
      headers: 
       apikey: string
      queryParameters: 
        customerId: number
      description: Fetch all orders if available.
      displayName: Get all orders
      responses:
        200:
          body: 
            application/json:
              example: !include examples/Orders.raml
        400:
          body: 
            application/json:
              example: !include examples/400Example.raml
        404:
          body: 
            application/json:
              example: !include examples/404Example.raml
        503:
          body: 
            application/json:
              example: !include examples/503Example.raml
 post:
      headers: 
       apikey: string
      description: Add a new order to database.
      displayName: Create a new order
      body:
        application/json:
         schema: |
          {
            "title": "Order Schema",
            "type": "object",
            "properties": {
              "OrderDate": {
                "type": "number"
              },
              "OrderNumber": {
                "type": "number"
              },
              "CustomerId": {
                "type":"number"
              },
              "TotalAmount": {
                "type": "number"
              }
            },
            "required": ["OrderDate", "OrderNumber", "CustomerId", "TotalAmount"]
          }
         example: !include examples/Order.raml
      responses: 
          201:
            body: 
              application/json:
                example: |
                  {
                    "response": "Resource created"
                  }
          400:
            body: 
              application/json:
                example: !include examples/400Example.raml
          404:
            body: 
              application/json:
                example: !include examples/404Example.raml
          503:
            body: 
              application/json:
                example: !include examples/503Example.raml
 /{ID}:
  get:
      headers: 
       apikey: string
      queryParameters: 
        customerId: number
      description: Fetch particular order details if available.
      displayName: Get particular order details
      responses:
        200:
          body: 
            application/json:
              example: !include examples/Order.raml
        400:
          body: 
            application/json:
              example: !include examples/400Example.raml
        404:
          body: 
            application/json:
              example: !include examples/404Example.raml
        503:
          body: 
            application/json:
              example: !include examples/503Example.raml    
  delete:
      headers: 
       apikey: string
      description: Remove salesman entity.
      displayName: Delete salesman.
      responses: 
            204:
              body: 
                application/json:
                  example: {}
            400:
              body: 
                application/json:
                  example: !include examples/400Example.raml
            404:
              body: 
                application/json:
                  example: !include examples/404Example.raml
            503:
              body: 
                application/json:
                  example: !include examples/503Example.raml